default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: freeme_development
test:
  <<: *default
  database: freeme_test
production:
  <<: *default
  database: freeme_production
  username: freeme
  password: <%= ENV['FREEME_DATABASE_PASSWORD'] %>
